sudo: required
before_install:
  # Install latest version docker CE
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  - docker version
  # Install latest version of docker-compose
  #- sudo apt-get update -qq
  #- sudo apt-get install -qq python-pip && pip install --upgrade pip
  #- sudo pip install docker-compose
  #- docker-compose version
services:
  - docker

before_script:
  # https://www.elastic.co/guide/en/elasticsearch/reference/5.0/vm-max-map-count.html
  - sudo sysctl -w vm.max_map_count=262144

script:
  - docker swarm init
  - docker node ls
  - chmod +x *.sh
  - ./deployStack.sh
  - sleep 180 #wait for the stack to come up
  - docker run -d --rm --name jenkins -p 8080:8080 --log-driver=gelf --log-opt gelf-address=udp://node1:12201 -v /var/run/docker.sock:/var/run/docker.sock jenkinsci/jenkins
  - sleep 120 #wait for the stack to come up

after_script:
  - docker stack services logging
  - docker stack ps logging
  #List all Elasticsearch Indices. One entry sould be for logstash containing console logs for Jenkins
  - curl -XGET -u elastic:changeme '127.0.0.1:9200/_cat/indices?v&pretty'
  - ./removeStack.sh
