version: "3.1"
 
services:
                
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2  
        volumes:
            - elasticsearchData:/usr/share/elasticsearch/data
        networks:
            - logging
        environment:
            xpack.security.enabled: "false"
            xpack.monitoring.enabled: "false"
            xpack.graph.enabled: "false"
            xpack.watcher.enabled: "false"
            
    logstash:
        image: docker.elastic.co/logstash/logstash:5.2.2
        ports:
          - "12201:12201/udp"
        networks:
            - logging
        volumes:
            - ./elk/logstash/config/pipeline:/usr/share/logstash/pipeline
            - ./elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
        
    kibana:
        image: docker.elastic.co/kibana/kibana:5.2.2
        ports:
            - 5601:5601
        networks:
            - logging
        volumes:
            - ./elk/kibana/config:/usr/share/kibana/config
      
networks:
    logging:
 
volumes:
    elasticsearchData:
