version: "3.1"
 
services:
                
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2  
        volumes:
            - elasticsearchData:/usr/share/elasticsearch/data
        networks:
            - logging
            
    logstash:
        image: docker.elastic.co/logstash/logstash:5.2.2
        ports:
          - "12201:12201/udp"
        networks:
            - logging
        volumes:
            - ./elk/logstash/config/pipeline:/usr/share/logstash/pipeline
        
    kibana:
        image: docker.elastic.co/kibana/kibana:5.2.2
        ports:
            - 5601:5601
        networks:
            - logging
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200

networks:
    logging:

volumes:
    elasticsearchData: