version: "3.3"

# 10 Things to Consider When Planning Your Elasticsearch Project: https://ecmarchitect.com/archives/2015/07/27/4031
# Using Apache JMeter to Test Elasticsearch: https://ecmarchitect.com/archives/2014/09/02/3915

services:

    # A node that has node.master set to true (default), which makes it eligible to be elected as the master node, which controls the cluster.
    elasticsearch_master:
        image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-5.6.2}
        hostname: elasticsearch_master
        environment:
            - cluster.name=elasticsearch-dev
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - node.name=elasticsearch_master
            - node.master=true
            - discovery.zen.minimum_master_nodes=1
        networks:
            - elastic
        volumes:
            - elasticsearch_master:/usr/share/elasticsearch/data

    # A node that has node.data set to true (default). Data nodes hold data and perform data related operations such as CRUD, search, and aggregations.
    elasticsearch_data:
        image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-5.6.2}
        hostname: elasticsearch_data
        environment:
            - cluster.name=elasticsearch-dev
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - node.name=elasticsearch_data
            - node.data=true
            - "discovery.zen.ping.unicast.hosts=elasticsearch_master"
        networks:
            - elastic
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data

    # A node that has node.ingest set to true (default). Ingest nodes are able to apply an ingest pipeline (https://www.elastic.co/guide/en/elasticsearch/reference/current/pipeline.html) to a document in order to transform and enrich the document before indexing. With a heavy ingest load, it makes sense to use dedicated ingest nodes and to mark the master and data nodes as node.ingest: false.
    elasticsearch_ingest:
        image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-5.6.2}
        hostname: elasticsearch_ingest
        ports:
            - "9200:9200"
        environment:
            - cluster.name=elasticsearch-dev
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - node.name=elasticsearch_ingest
            - node.ingest=true
            - "discovery.zen.ping.unicast.hosts=elasticsearch_master"
        networks:
            - elastic
        volumes:
            - elasticsearch_ingest:/usr/share/elasticsearch/data

    logstash:
        image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION:-5.6.2}
        hostname: logstash
        ports:
          - "12201:12201/udp"
        networks:
            - elastic
        volumes:
            - ./elk/logstash/config/pipeline:/usr/share/logstash/pipeline

    kibana:
        image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION:-5.6.2}
        hostname: kibana
        ports:
            - "5601:5601"
        networks:
            - elastic
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch_ingest:9200

networks:
    elastic:

volumes:
    elasticsearch_master:
    elasticsearch_data:
    elasticsearch_ingest:
