version: "3.1"

services:

    logstash:
        image: docker.elastic.co/logstash/logstash:${ELK_VERSION}
        ports:
          - "12201:12201/udp"
        networks:
            - logging
        volumes:
            - ./elk/logstash/config/pipeline:/usr/share/logstash/pipeline

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
        ports:
            - 9200:9200
        volumes:
            - elasticsearchData:/usr/share/elasticsearch/data
        networks:
            - logging

    kibana:
        image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
        ports:
            - 5601:5601
        networks:
            - logging
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200

environment:
  - ELK_VERSION=5.4.0

networks:
    logging:

volumes:
    elasticsearchData:
