version: "3.1"

services:

    logstash:
        image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}
        hostname: logstash
        ports:
          - "12201:12201/udp"
        networks:
            - logging
        volumes:
            - ./elk/logstash/config/pipeline:/usr/share/logstash/pipeline

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
        hostname: elasticsearch
        ports:
            - 9200:9200
        volumes:
            - elasticsearchData:/usr/share/elasticsearch/data
        networks:
            - logging

    kibana:
        image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
        hostname: kibana
        ports:
            - 5601:5601
        networks:
            - logging
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200

    metricbeat:
        image: quay.io/shazchaudhry/docker-metricbeat
        hostname: metricbeat
        volumes:
          - metricmeat_data:/var/lib/metricmeat
          - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - logging
        environment:
          - HOST=elasticsearch
          - PORT=9200
          - PROTOCOL=http
          - USERNAME=elastic
          - PASSWORD=changeme
        deploy:
            mode: global

networks:
    logging:

volumes:
    elasticsearchData:
    metricmeat_data:
