filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - '/var/lib/docker/containers/*/*.log'
  json.message_key: log
  json.add_error_key: true
  json.keys_under_root: true
  processors:
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"
    - add_cloud_metadata: ~
    - add_locale: ~
  multiline.pattern: "^\t|^[[:space:]]+(at|...)|^Caused by:"
  multiline.match: after
# - type: log
#   enabled: true
#   paths:
#     # path to jenkins build logs
#     - /var/lib/docker/volumes/jenkins_home/_data/jobs/*/builds/*/log
#   json.message_key: log
#   json.add_error_key: true
#   json.keys_under_root: true
#   multiline.pattern: '^[[:space:]]+|^Caused by:'
#   multiline.negate: false
#   multiline.match: after

#==========================  Modules configuration ============================
filebeat.modules:

#------------------------------- System Module -------------------------------
- module: system
  # Syslog
  syslog:
    enabled: true
  auth:
    enabled: true

#------------------------------- Auditd Module -------------------------------
- module: auditd
  log:
    enabled: false

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: elastic
  password: changeme

#============================== Dashboards =====================================
setup.dashboards.enabled: true
setup.kibana:
  host: "kibana:5601"
  username: elastic
  password: changeme
