packetbeat.interfaces.device: any

packetbeat.protocols:

- type: http
  ports: [80, 8080, 8081, 5000, 8002, 9200, 5601]
  hide_keywords: ["pass", "password", "passwd"]
  send_headers: ["User-Agent", "Cookie", "Set-Cookie"]
  split_cookie: true
  real_ip_header: "X-Forwarded-For"

- type: pgsql
  ports: [5432]

- type: redis
  ports: [6379]

- type: tls
  ports: [443]

packetbeat.flows:
  timeout: 30s
  period: 10s

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  hosts: ["${HOST}:9200"]
  username: elastic
  password: changeme

xpack.monitoring:
  enabled: true
  elasticsearch:

#============================== Dashboards =====================================
# These settings control loading the sample dashboards to the Kibana index.
# Loading the dashboards is disabled by default and can be enabled either by setting the options here, or by using the `-setup` CLI flag.
setup.dashboards:
  enabled: true
setup.kibana:
  host: "${HOST}:5601"
  username: elastic
  password: changeme
